### PR TITLE
update to recent experimental

### PR DESCRIPTION
**Pull request by nornagon**
Did some work to make a build on the latest experimental, thought I'd share :)

Wasn't too hard—just had to update the file list and add a system include path
for the new src/third-party directory.

Also changed the patch script to work properly when rebuilding.

### CODE REVIEW

**Comment by apollovy** [comment]
Hey, @nornagon .

The reason under why I don't publish unstable to App Store is because, well, it's unstable. I won't update 0.F to any version that is different from official 0.F except for maybe some with bugfixes backports. Experimental is known for issues that might exist for quite a long time. Also I do have at least 2 versions, 0.E and 0.F, because some features in 0.F are not that pleasant for some part of gamers, and App Store doesn't allow to install older versions of the app. When 0.G will arrive, I'll certainly create a separate app in the App Store and have a separate branch to maintain it.

I can merge your PR into, say, experimental branch.

**Comment by nornagon** [comment]
@apollovy makes sense! I didn't see an experimental branch when I was making the PR, but it looks like you've changed it now.

I understand you're not interested in publishing a version based on experimental CDDA to the App Store. Would you mind if I published one?

**Comment by apollovy** [comment]
> I understand you're not interested in publishing a version based on experimental CDDA to the App Store. Would you mind if I published one?
We can go different ways:
- if you wish to maintain and update this version, then I'd be happy to add a new app for Experimental to my account and give you the necessary permissions to do all the things. This is if we wanted to keep all the apps in the single place
- if you wish the Experimental to be published under your own account — well, I'd be not that happy, but still this is your right to do it, since it's opensource and license permits it :)

**Comment by nornagon** [comment]
@apollovy I'd be okay with putting it under your account as long as it was published free. It doesn't feel right to me to donate my effort and have the proceeds go to someone else, and it seems like it would probably be quite challenging to set up a profit-sharing system if it were not free, given international tax law and so on. On the other hand, if I were to end up putting it on my own developer account, I'd be happy to give credit to you and coordinate with you on pricing and the like. Basically, a way for us to collaborate and share proceeds but have Apple do the work of figuring out the tax stuff for us :)

What do you think about those options?

**Comment by apollovy** [comment]
@nornagon sorry for a long delay. I think that  it'll be okay if you would place the app for $5, given that CBN is receiving updates on regular basis too and cost this much. The only thing that comes to my mind is that in case  some of us will abandon our apps, we'll not be able to transfer them the easy way. At the same time, it's always possible to delete the old apps and create new ones 😃. Oh, the other thing that just came to my mind is that i won't be able to include your app into a bundle with all the versions available: https://apps.apple.com/app-bundle/id1622220695

**Comment by nornagon** [comment]
Alrighty, that seems reasonable to me!

By the way, did you see my other PR changing the build system? It’s a bit of a bigger change, but I think it will make keeping up with experimental much easier as I won’t have to open Xcode. In fact I think I can make the whole compile-publish flow run as a CI job 🤔

**Pull request closed without merging**
